language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- polymer lint events-target-mixin.html
- xvfb-run polymer test --module-resolution=node --npm polymer test --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node
  --npm --plugin sauce --job-name "events-target-mixin:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
env:
  global:
  - secure: Jk23D+GDpjskTGiHxidbThqSp3MWWcjm9aNqsvVgNlAPsclvimaictHVVSwUAzBCkqAV1H4PUl6MhZgSTUD5I7VKad9og8XGs/A+Hm2QjsG99a3Cl0fP8A6b7+dKbRRUhIsj8TjRaMjZ/CZrH5+uXWNHVh8ILlT6/ttiZPRy/9bHvB7RshYqruZ+HM++YUVjWC07t8a3j0uuugepAayPSkoRdLUCYGYvztwl8ZVN3oNI7H7xayqbLZmi7jy00gbLJy8SqWpDiif3BL35hL0op0FsFWgeoE5gE0Ux150hd7Hz4KglqIxtrfDfWszN7MqMPk6hUOcI80MVSyQ68RW1Xt4cLVF/6ylFf9Q9uda/Gqhq8495oiXfUNx8W1DPR/dMMOTjSVVdX3UhTWrXSiaCK+n7k9hKwfRW4Kh/TWngIheasV0fwNHSOnM52WxwjIKHJ1HrsGAU/MScnfW5esEYIjBZoo2XeLrfbAI3klm7JbOm2fO9ytKsNOaAlLVxltI0yonpsmVWGMYEhwIHd9Hn6yrVPNw+Fdwonrqjr9/XbFFWuIXgTwGZZp9p/irEDnvSU7lYkW9NY5Xb1hXaNP9O4obsNuodxduOGCGMJp8adNudGfhsUQJejSqIDF8ZCGwC9BvDuC0CWhfii3SjjQF6rcNjWLaaYvwUOTY+XYKL4vo=
  - secure: XLdf6aGJokDeH3t8NadVArb6BdJ8CRjUzLelbwihuy1Yaye6IsDnjRZj26ZeOqHnnydpG33ag5f7ozvmddoERDCdtwpCzVcXV94Mwi/z/gYXRzfQkb4PA1TibA2Q5gVS6uQbna+6pHoco1KD9pF9ku3impImuGphP9SiBc//yqZM/UggDagIGRi+mn5DytVXT7QDbbAe5KaEedXT07phmy9oAcw5zFYKAaXn89pHj3ljkxcRIglVzpHD+pgasvbD1kCW0mFxDyfC/gaGmbHrNExM7zUTTSWLbOvbNhQewxgclmzLAKIA2Zskh+ceMqKwwwwqH8BS+0KL3I4BMXV+rQ0ENLysPaLFTScyJw5juYbn49dCBgTq2m9UnLtL1F2jGeMYcpY9kInbGeR/aJihn7vZ+oIJixz5i4ahGaYVx9iGT2AtE+7tUogyFBNN6XB/3I50uOh/kp4njUsSiM+3aNn0L9/QabmfewB4bj7g+R6NyqMUVjTiO291+2H8HzxxANFTHmASo+b3eW6V5hnCLExoqilxgeWHUT9bstlN/S72IY4T6xz22iiNtCRjj+h6CuL/6s+P+8Tm/cYb407MEqN12GwE2qVvyTi3Prfc2Ud8MkJ25Fe+mmI8RrQ/hBVNMuoMThO66t36frBEzfjklXoE5ARb017FdEMaSoUcfyY=
